/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.marcher.quarto.ui;

import dk.marcher.quarto.logic.Board;
import dk.marcher.quarto.ui.listeners.BoardListener;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.LineBorder;

/**
 *
 * @author marcher89
 */
public class BoardPanel extends javax.swing.JPanel {

    private JLabel[] labels = new JLabel[16];
    private final BoardListener boardListener;

    /**
     * Only used for Netbeans GUI
     */
    public BoardPanel(){
        this(null);
    }
    
    /**
     * Creates new form BoardPanel
     */
    public BoardPanel(BoardListener boardListener) {
        this.boardListener = boardListener;
        initComponents();
        for (int i = 0; i < 16; i++) {
            labels[i] = new JLabel(new ImageIcon(PieceUI.getBlankImage()));
            labels[i].setBorder(new LineBorder(Color.BLACK, 2));
            add(labels[i]);
        }
    }

    public void setPiece(int x, int y, int piece) {
        labels[y * 4 + x].setIcon(new ImageIcon(PieceUI.getPieceImage(piece)));
    }

    public void clearBoard() {
        for (JLabel label : labels) {
            label.setIcon(new ImageIcon(PieceUI.getBlankImage()));
            label.setBorder(new LineBorder(Color.BLACK, 2));
        }
    }

    public void markQuarto(int[][] quartoSquares) {
        for (int[] sq : quartoSquares) {
            labels[sq[0] + sq[1] * 4].setBorder(new LineBorder(Color.YELLOW, 2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardClicked(evt);
            }
        });
        setLayout(new java.awt.GridLayout(4, 4));
    }// </editor-fold>//GEN-END:initComponents

    private void boardClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardClicked

        Dimension boardSize = getSize();
        Point location = evt.getPoint();
        int relX = (int) (location.getX() / boardSize.getWidth() * 4);
        int relY = (int) (location.getY() / boardSize.getHeight() * 4);

        boardListener.squareChosen(relX, relY);

    }//GEN-LAST:event_boardClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
