/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.marcher.quarto.ui;

import dk.marcher.quarto.controller.QuartoController;
import dk.marcher.quarto.ui.listeners.*;

/**
 *
 * @author marcher89
 */
public class GamePanel extends javax.swing.JPanel {

    private final QuartoController quartoController;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        quartoController = new QuartoController(this);
        initComponents();
    }

    public BoardPanel getBoardPanel() {
        return boardPanel;
    }

    public PlayerPanel getPlayerPanel() {
        return playerPanel;
    }

    public PoolPanel getPoolPanel() {
        return poolPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poolPanel = new dk.marcher.quarto.ui.PoolPanel(new PoolListener() {
            @Override
            public void pieceChosen(int piece) {
                quartoController.pieceChosen(piece);
            }
        });
        boardPanel = new dk.marcher.quarto.ui.BoardPanel(new BoardListener() {
            @Override
            public void squareChosen(int x, int y) {
                quartoController.squareChosen(x,y);
            }
        });
        playerPanel = new dk.marcher.quarto.ui.PlayerPanel();

        setLayout(new java.awt.BorderLayout());
        add(poolPanel, java.awt.BorderLayout.NORTH);
        add(boardPanel, java.awt.BorderLayout.CENTER);
        add(playerPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dk.marcher.quarto.ui.BoardPanel boardPanel;
    private dk.marcher.quarto.ui.PlayerPanel playerPanel;
    private dk.marcher.quarto.ui.PoolPanel poolPanel;
    // End of variables declaration//GEN-END:variables

    void newGame() {
        quartoController.newGame();
    }

}
