/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.marcher.quarto.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author marcher89
 */
public class PlayerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel() {
        initComponents();
    }

    public void setPieceToPlace(int piece) {
        pieceToPlaceLabel.setIcon(new ImageIcon(PieceUI.getPieceImage(piece)));
    }
    
    public void removePieceToPlace() {
        pieceToPlaceLabel.setIcon(new ImageIcon(PieceUI.getBlankImage()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pieceToPlaceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 241, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 118, Short.MAX_VALUE)
        );

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        pieceToPlaceLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pieceToPlaceLabel.setMaximumSize(new java.awt.Dimension(45, 45));
        pieceToPlaceLabel.setMinimumSize(new java.awt.Dimension(45, 45));
        pieceToPlaceLabel.setPreferredSize(new java.awt.Dimension(45, 45));
        pieceToPlaceLabel.setSize(new java.awt.Dimension(45, 45));
        jPanel2.add(pieceToPlaceLabel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Piece to Place");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel2.add(jLabel1, java.awt.BorderLayout.WEST);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pieceToPlaceLabel;
    // End of variables declaration//GEN-END:variables
}
