/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.marcher.quarto.ui;

import dk.marcher.quarto.ui.listeners.*;

/**
 *
 * @author marcher89
 */
public class QuartoMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form QuartoMainWindow
     */
    public QuartoMainWindow() {
        initComponents();
        gamePanel.newGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePanel = new dk.marcher.quarto.ui.GamePanel();
        menuPanel = new javax.swing.JPanel();
        newGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);

        menuPanel.setBackground(new java.awt.Color(204, 102, 0));
        menuPanel.setLayout(new javax.swing.BoxLayout(menuPanel, javax.swing.BoxLayout.Y_AXIS));

        newGameButton.setText("New Game");
        newGameButton.setMaximumSize(new java.awt.Dimension(120, 30));
        newGameButton.setMinimumSize(new java.awt.Dimension(120, 30));
        newGameButton.setPreferredSize(new java.awt.Dimension(120, 30));
        newGameButton.setSize(new java.awt.Dimension(120, 30));
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameClicked(evt);
            }
        });
        menuPanel.add(newGameButton);

        exitButton.setText("Exit");
        exitButton.setMaximumSize(new java.awt.Dimension(120, 30));
        exitButton.setMinimumSize(new java.awt.Dimension(120, 30));
        exitButton.setPreferredSize(new java.awt.Dimension(120, 30));
        exitButton.setSize(new java.awt.Dimension(120, 30));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitClicked(evt);
            }
        });
        menuPanel.add(exitButton);

        getContentPane().add(menuPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitClicked
        System.exit(0);
    }//GEN-LAST:event_exitClicked

    private void newGameClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameClicked
        gamePanel.newGame();
    }//GEN-LAST:event_newGameClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuartoMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuartoMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuartoMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuartoMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuartoMainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private dk.marcher.quarto.ui.GamePanel gamePanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables
}
